drivers: Move more SECTOR_SIZE definitions into <linux/blkdev.h>
Introduces after d24c407b0f7af675a3928fdd4121306ad32c60ab.

Fix error:

    ../drivers/md/dm-req-crypt.c:54:9: error: 'SECTOR_SIZE' macro redefined [-Werror,-Wmacro-redefined]
            ^
    ../include/linux/blkdev.h:871:9: note: previous definition is here
            ^
    1 error generated.
    make[3]: *** [../scripts/Makefile.build:340: drivers/md/dm-req-crypt.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
      CC      drivers/media/platform/msm/sde/rotator/sde_rotator_r3.o
      CC      drivers/media/platform/msm/sde/rotator/sde_rotator_sync.o
    ../drivers/md/dm-bow.c:15:9: error: 'SECTOR_SIZE' macro redefined [-Werror,-Wmacro-redefined]
            ^
    ../include/linux/blkdev.h:871:9: note: previous definition is here
            ^
    1 error generated.

Signed-off-by: TsingPeng <tsingpeng@foxmail.com>